apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: assetgen

resources:
  - namespace.yaml
  - secrets.yaml
  - deployment.yaml
  - ingress.yaml
  - gpu-waker.yaml
  - keda-gpu-waker.yaml
